server:
  port: 8080
  servlet:
    context-path: /whats-api
spring:
  datasource:
    url: jdbc:h2:~/whats-api
    driver-class-name: org.h2.Driver
    username: root
    password: root
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true